# Tests for Exercise 02
# Written by your teacher. Do not edit this file.
# Run: pytest

from solution import classify_score, fizzbuzz, can_vote, absolute_value, largest

# --- Your teacher will fill in the test cases below ---
